services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: picpay_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db_mysql:/var/lib/mysql
volumes:
  db_mysql:
